### ISSUE TITLE
May I repost this  with Chinese?

### ISSUE THREAD

**Issue by shincling** [sergeyprokudin/PolicyGradient#1]
HI , bro. I am a PhD student from china. Thx a lot for this repository that i have learned from it .
Cause there has no much good resource in chinese about Policy Gradient methods , so I want to repost  this in chinese with a blog to introduce it .

Could you agree this ? 
Thx again.

**Comment by sergeyprokudin** [comment]
Hi, 

Yes, of course. Glad to know that it helped you!

**Comment by shincling** [comment]
Appreciate for your kindness ! 
It's very userful ~! 
Thank you !
